pagination:
  per: 25
  max_per: 100
subscriptions:
  resources:
    - devices
    - types
    - locations
  events:
    - property-updated
    - consumption-created
    - created
    - updated
    - deleted

